# Generated by Django 3.2.14 on 2022-08-15 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('ACTI_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ACTI_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'ACTIVIDAD_ECONOMICA',
            },
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('ASES_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('TIAS_CODIGO', models.PositiveIntegerField()),
                ('ASE_ASES_CODIGO', models.PositiveIntegerField(null=True)),
                ('TIBA_CODIGO', models.PositiveIntegerField()),
                ('ZONA_CODIGO', models.PositiveIntegerField()),
                ('EMPR_CODIGO', models.CharField(max_length=10)),
                ('AGEN_CODIGO', models.PositiveIntegerField()),
                ('USUA_CODIGO', models.CharField(max_length=20)),
                ('ASES_NOMBRE', models.CharField(max_length=40)),
                ('ASES_CLAVE', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'ASESOR',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('BANC_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('BANC_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'BANCO',
            },
        ),
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('PROV_CODIGO', models.CharField(max_length=5)),
                ('CANT_CODIGO', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('CANT_NOMBRE', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CANTON',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('CLIE_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('NACI_CODIGO', models.PositiveIntegerField()),
                ('TICL_CODIGO', models.CharField(max_length=2)),
                ('TIDO_CODIGO', models.CharField(max_length=2)),
                ('ACTI_CODIGO', models.PositiveIntegerField()),
                ('ASES_CODIGO', models.PositiveIntegerField()),
                ('CLIE_IDENTIFICACION', models.CharField(max_length=20)),
                ('CLIE_NOMBRE', models.CharField(max_length=60, null=True)),
                ('CLIE_FECHA_CREACION', models.DateTimeField(null=True)),
                ('CLIE_NOMBRE_CORRESPONDENCIA', models.CharField(max_length=40)),
                ('clie_estado', models.CharField(max_length=1, null=True)),
                ('TISB_CODIGO', models.PositiveIntegerField(null=True)),
                ('clie_tipo', models.CharField(max_length=1, null=True)),
                ('CLIE_CLAVE', models.CharField(max_length=20, null=True)),
                ('CLIE_TIPO_ROL', models.CharField(max_length=2, null=True)),
                ('CLIE_TIPO_PROYECTO', models.PositiveIntegerField(null=True)),
                ('comodin', models.PositiveIntegerField(null=True)),
                ('ASES', models.PositiveIntegerField(null=True)),
                ('CLIE_FECHA_INACTIVACION', models.DateTimeField(null=True)),
                ('CLIE_FECHA_DESAFILIACION', models.DateTimeField(null=True)),
                ('sect_codigo', models.CharField(max_length=5, null=True)),
                ('pais_codigo', models.CharField(max_length=3, null=True)),
                ('prov_codigo', models.CharField(max_length=3, null=True)),
                ('cant_codigo', models.CharField(max_length=5, null=True)),
                ('parr_codigo', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='ClienteJuridico',
            fields=[
                ('CLIE_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('TIEM_CODIGO', models.PositiveIntegerField()),
                ('GREC_CODIGO', models.PositiveIntegerField()),
                ('CLI_CLIE_CODIGO', models.PositiveIntegerField()),
                ('CLJU_NOMBRE_PUBLICITARIO', models.CharField(max_length=80)),
                ('CLJU_RAZON_SOCIAL', models.CharField(max_length=40)),
                ('CLJU_REPRESENTANTE', models.CharField(max_length=40)),
                ('CLJU_FECHA_CONSTITUCION', models.DateTimeField()),
                ('CLJU_CAPITAL_SUS', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CLJU_CAPITAL_PAG', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CLJU_FECREF_STA', models.DateTimeField()),
                ('CLJU_RESERVA_LEG', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CLJU_CARGO_REPRESENTANTE', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'CLIENTE_JURIDICO',
            },
        ),
        migrations.CreateModel(
            name='ClienteNatural',
            fields=[
                ('CLIE_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('PROF_CODIGO', models.PositiveIntegerField()),
                ('NIIN_CODIGO', models.PositiveIntegerField()),
                ('SEXO_CODIGO', models.CharField(max_length=2)),
                ('ESCI_CODIGO', models.PositiveIntegerField()),
                ('CLNA_NOMBRE1', models.CharField(max_length=40)),
                ('CLNA_NOMBRE2', models.CharField(max_length=40, null=True)),
                ('CLNA_APELLIDO1', models.CharField(max_length=40)),
                ('CLNA_APELLIDO2', models.CharField(max_length=40, null=True)),
                ('CLNA_FECHA_NACIMIENTO', models.DateTimeField()),
                ('CLNA_LUGAR_NACIMIENTO', models.CharField(max_length=40)),
                ('CLIE_TIPO_VIVIENDA', models.PositiveIntegerField(null=True)),
                ('CLIE_SITUACION_LABORAL', models.PositiveIntegerField(null=True)),
                ('CLNA_EXPIRA_PASAPORTE', models.DateTimeField(null=True)),
                ('CLNA_INICIO_RESIDENCIA', models.DateTimeField(null=True)),
                ('CLNA_NUM_CARGAS', models.PositiveIntegerField(null=True)),
                ('CLNA_EMPRESA_TRABAJA', models.CharField(max_length=60, null=True)),
                ('CLNA_INICIO_INGRESOS', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'CLIENTE_NATURAL',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancariaCliente',
            fields=[
                ('CLIE_CODIGO', models.PositiveIntegerField()),
                ('CUBC_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('BANC_CODIGO', models.PositiveIntegerField()),
                ('TICU_CODIGO', models.PositiveIntegerField()),
                ('CUBC_CUENTA', models.CharField(max_length=20)),
                ('CUBC_CUENTA_CONTABLE', models.CharField(max_length=40, null=True)),
                ('PROPIETARIO_CUENTA', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'CUENTA_BANCARIA_CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('ESCI_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('ESCI_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'ESTADO_CIVIL',
            },
        ),
        migrations.CreateModel(
            name='GrupoEconomico',
            fields=[
                ('GREC_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('GREC_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'GRUPO_ECONOMICO',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('MONE_CODIGO', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('MONE_DESCRIPCION', models.CharField(max_length=40)),
                ('MONE_DECIMALES', models.PositiveIntegerField()),
                ('MONE_ALIAS', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'MONEDA',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('NACI_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('NACI_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'NACIONALIDAD',
            },
        ),
        migrations.CreateModel(
            name='NivelInstruccion',
            fields=[
                ('NIIN_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('NIIN_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'NIVEL_INSTRUCCION',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('CLIE_CODIGO', models.PositiveIntegerField()),
                ('OBCL_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('TIOC_CODIGO', models.PositiveIntegerField()),
                ('OBCL_DESCRI', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'OBSERVACION_CLIENTES',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('PAIS_CODIGO', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('PAIS_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'PAIS',
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('PROV_CODIGO', models.CharField(max_length=5)),
                ('CANT_CODIGO', models.CharField(max_length=5)),
                ('PARR_CODIGO', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('PARR_NOMBRE', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PARROQUIA',
            },
        ),
        migrations.CreateModel(
            name='Periocidad',
            fields=[
                ('PERI_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('PERI_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'PERIOCIDAD',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('PROF_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('PROF_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'PROFESION',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('PAIS_CODIGO', models.CharField(max_length=3)),
                ('PROV_CODIGO', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('PROV_NOMBRE', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PROVINCIA',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('SEXO_CODIGO', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('SEXO_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'SEXO',
            },
        ),
        migrations.CreateModel(
            name='SituacionLaboral',
            fields=[
                ('SITL_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('SITL_DESCRIPCION', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SITUACION_LABORAL',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('TELE_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('TITE_CODIGO', models.PositiveIntegerField()),
                ('TIDE_CODIGO', models.PositiveIntegerField()),
                ('CLIE_CODIGO', models.PositiveIntegerField()),
                ('DIRE_CODIGO', models.PositiveIntegerField()),
                ('TELE_NUMERO', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TELEFONO',
            },
        ),
        migrations.CreateModel(
            name='TipoAgencia',
            fields=[
                ('TIAG_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('TIAG_DESCRIPCION', models.CharField(max_length=40)),
                ('TIAG_CENTRO_CANJE', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'TIPO_AGENCIA',
            },
        ),
        migrations.CreateModel(
            name='TipoAsesor',
            fields=[
                ('TIAS_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('TIAS_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TIPO_ASESOR',
            },
        ),
        migrations.CreateModel(
            name='TipoBanca',
            fields=[
                ('TIBA_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('TIBA_DESCRIPCION', models.CharField(max_length=40)),
                ('TIBA_RESPONSABLE', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TIPO_DE_BANCA',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('TICL_CODIGO', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('TICL_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TIPO_CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('TICU_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('TICU_DESCRIPCION', models.CharField(max_length=40)),
                ('TICU_CODIGO_ALT', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'TIPO_CUENTA',
            },
        ),
        migrations.CreateModel(
            name='TipoCuentaBalance',
            fields=[
                ('TICB_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('TICB_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TIPO_CUENTA_BALANCE',
            },
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('TIDE_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('TIDE_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TIPO_DIRECCION',
            },
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('TIEM_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('TIEM_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TIPO_EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='TipoObservacion',
            fields=[
                ('TIOC_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('TIOC_DESCRI', models.CharField(max_length=40)),
                ('TIOC_CAMBIO', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'TIPO_OBSERVACION_CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('COD_TIPO_PROYECTO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('DESC_TIPO_PROYECTO', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'CLIE_TIPO_PROYECTO',
            },
        ),
        migrations.CreateModel(
            name='TipoRol',
            fields=[
                ('TIRO_CODIGO', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('TIROL_DESCRIPCIÒN', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TIPO_ROL',
            },
        ),
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('TITE_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('TITE_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TIPO_TELEFONO',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('USUA_CODIGO', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ESUS_CODIGO', models.PositiveIntegerField()),
                ('USUA_NOMBRE', models.CharField(max_length=40)),
                ('USUA_CLAVE', models.CharField(max_length=20)),
                ('USUA_FECHA_CREACION', models.DateTimeField()),
                ('USUA_FECHA_INICIO', models.DateTimeField()),
                ('USUA_FECHA_FIN', models.DateTimeField()),
                ('USUA_LOGIN', models.CharField(max_length=20)),
                ('ZONA_CODIGO', models.PositiveIntegerField()),
                ('EMPR_CODIGO', models.CharField(max_length=10)),
                ('AGEN_CODIGO', models.PositiveIntegerField()),
                ('CETC_CODIGO', models.PositiveIntegerField()),
                ('USUA_IDENTIFICACION', models.CharField(max_length=15)),
                ('USUA_PERIOCIDAD', models.PositiveIntegerField()),
                ('USUA_ADMINISTRADOR', models.CharField(max_length=1)),
                ('USUA_CARGO', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('VIVI_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('VIVI_DESCRIPCION', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'VIVIENDA',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('ZONA_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('ZONA_DESCRIPCION', models.CharField(max_length=40)),
                ('PAIS_CODIGO', models.ForeignKey(db_column='PAIS_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.pais')),
            ],
            options={
                'db_table': 'ZONA',
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('CLIE_CODIGO', models.PositiveIntegerField()),
                ('VINC_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('TICL_CODIGO', models.CharField(max_length=2)),
                ('TIVI_CODIGO', models.PositiveIntegerField()),
                ('VINC_IDENTIFICACION', models.CharField(max_length=20)),
                ('VINC_NOMBRE', models.CharField(max_length=60, null=True)),
                ('VINC_DIRECCION', models.CharField(max_length=80)),
                ('VINC_TELEFONO', models.CharField(max_length=40)),
                ('VINC_OBSERVA', models.CharField(max_length=400, null=True)),
                ('VIN_USUARIO_INGRESA', models.CharField(max_length=50, null=True)),
                ('VIN_FECHA_INGRESA', models.DateTimeField(null=True)),
                ('VIN_ESTADO', models.CharField(max_length=1, null=True)),
                ('NACI_CODIGO', models.PositiveIntegerField(null=True)),
                ('PROF_CODIGO', models.PositiveIntegerField(null=True)),
                ('VINC_CARGO', models.CharField(max_length=40, null=True)),
                ('CIUD_CODIGO', models.PositiveIntegerField(null=True)),
                ('esci_codigo', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'VINCULO',
                'unique_together': {('CLIE_CODIGO', 'VINC_CODIGO')},
            },
        ),
        migrations.CreateModel(
            name='VehiculoLegal',
            fields=[
                ('VELE_CODIGO', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('VELE_DESCRIPCION', models.CharField(max_length=40)),
                ('PAIS_CODIGO', models.ForeignKey(db_column='PAIS_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.pais')),
            ],
            options={
                'db_table': 'VEHICULO_LEGAL',
            },
        ),
        migrations.CreateModel(
            name='TipoVinculo',
            fields=[
                ('TICL_CODIGO', models.CharField(max_length=2)),
                ('TIVI_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('TIVI_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TIPO_VINCULO',
                'unique_together': {('TICL_CODIGO', 'TIVI_CODIGO')},
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('TICL_CODIGO', models.PositiveIntegerField()),
                ('TIDO_CODIGO', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('TIDO_DESCRIPCION', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TIPO_DOCUMENTO',
                'unique_together': {('TICL_CODIGO', 'TIDO_CODIGO')},
            },
        ),
        migrations.CreateModel(
            name='SubtipoEmpresa',
            fields=[
                ('SUTE_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('SUTE_DESCRIPCION', models.CharField(max_length=40)),
                ('TIEM_CODIGO', models.ForeignKey(db_column='TIEM_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.tipoempresa')),
            ],
            options={
                'db_table': 'SUB_TIPO_EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='Secuencia',
            fields=[
                ('EMPR_CODIGO', models.CharField(max_length=10, null=True)),
                ('SECU_TABLA', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('SECU_VALOR_ACTUAL', models.PositiveIntegerField()),
                ('SECU_PASO', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'SECUENCIAS',
                'unique_together': {('EMPR_CODIGO', 'SECU_TABLA')},
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('EMPR_CODIGO', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('EMP_EMPR_CODIGO', models.CharField(max_length=10, null=True)),
                ('EMPR_NOMBRE', models.CharField(max_length=80)),
                ('EMPR_IDENTIFICACION', models.CharField(max_length=20)),
                ('EMPR_FECHA_CONSTITUCION', models.DateTimeField()),
                ('EMPR_FECHA_CREACION', models.DateTimeField()),
                ('EMPR_DIRECCION', models.CharField(max_length=80)),
                ('FECHA_ACTUAL', models.DateTimeField()),
                ('FECHA_ANTERIOR', models.DateTimeField()),
                ('FECHA_SIGUIENTE', models.DateTimeField()),
                ('FECHA_CIERRE', models.DateTimeField(null=True)),
                ('EMPR_VIGENTE', models.CharField(max_length=1)),
                ('EMPR_PERIOCIDAD', models.PositiveIntegerField()),
                ('EMPR_CODIGO_SUPER', models.CharField(max_length=20, null=True)),
                ('empr_rep_legal', models.CharField(max_length=50, null=True)),
                ('empr_cargo', models.CharField(max_length=30, null=True)),
                ('autorizacion_sri', models.CharField(max_length=30, null=True)),
                ('contribuyente_esp', models.CharField(max_length=50, null=True)),
                ('empr_fecha_emision', models.CharField(max_length=30, null=True)),
                ('EMPR_IMPRIME_IMAGEN', models.PositiveIntegerField(null=True)),
                ('EMPR_IMAGEN', models.CharField(max_length=50, null=True)),
                ('GREM_CODIGO', models.ForeignKey(db_column='GREM_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.grupoeconomico')),
                ('MONE_CODIGO', models.ForeignKey(db_column='MONE_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.moneda')),
                ('PERI_CODIGO', models.ForeignKey(db_column='PERI_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.periocidad')),
                ('SUTE_CODIGO', models.ForeignKey(db_column='SUTE_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.subtipoempresa')),
                ('TIEM_CODIGO', models.ForeignKey(db_column='TIEM_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.tipoempresa')),
                ('VELE_CODIGO', models.ForeignKey(db_column='VELE_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.vehiculolegal')),
            ],
            options={
                'db_table': 'EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('TIDE_CODIGO', models.PositiveIntegerField()),
                ('CLIE_CODIGO', models.PositiveIntegerField()),
                ('DIRE_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('CIUD_CODIGO', models.PositiveIntegerField()),
                ('DIRE_DESCRIPCION', models.CharField(max_length=250, null=True)),
                ('prov_codigo', models.CharField(max_length=5, null=True)),
                ('cant_codigo', models.CharField(max_length=5, null=True)),
                ('parr_codigo', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'DIRECCION',
                'unique_together': {('CLIE_CODIGO', 'DIRE_CODIGO')},
            },
        ),
        migrations.CreateModel(
            name='CuentaBalance',
            fields=[
                ('CUBA_CUENTA', models.AutoField(primary_key=True, serialize=False)),
                ('CUBA_DESCRIPCION', models.CharField(max_length=40)),
                ('TICB_CODIGO', models.ForeignKey(db_column='TICB_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.tipocuentabalance')),
            ],
            options={
                'db_table': 'CUENTA_BALANCE',
            },
        ),
        migrations.CreateModel(
            name='ClienteAsesor',
            fields=[
                ('CLIE_CODIGO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ASES_CODIGO', models.PositiveIntegerField()),
                ('EMPR_CODIGO', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'CLIENTE_ASESOR',
                'unique_together': {('CLIE_CODIGO', 'ASES_CODIGO')},
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('CIUD_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('CIUD_NOMBRE', models.CharField(max_length=50)),
                ('ZONA_CODIGO', models.ForeignKey(db_column='ZONA_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.zona')),
            ],
            options={
                'db_table': 'CIUDAD',
            },
        ),
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('AGEN_CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('AGEN_DESCRIPCION', models.CharField(max_length=40)),
                ('AGEN_DIRECCION', models.CharField(max_length=40)),
                ('AGEN_RESPONSABLE', models.CharField(max_length=40)),
                ('AGEN_TELEFONO', models.CharField(max_length=40)),
                ('AGEN_CODIGO_SUPER', models.CharField(max_length=40, null=True)),
                ('CIUD_CODIGO', models.ForeignKey(db_column='CIUD_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.ciudad')),
                ('EMPR_CODIGO', models.ForeignKey(db_column='EMPR_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.empresa')),
                ('TIAG_CODIGO', models.ForeignKey(db_column='TIAG_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.tipoagencia')),
                ('ZONA_CODIGO', models.ForeignKey(db_column='ZONA_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.zona')),
            ],
            options={
                'db_table': 'AGENCIA',
            },
        ),
        migrations.CreateModel(
            name='BalanceCliente',
            fields=[
                ('BAEM_FECHA', models.DateTimeField(primary_key=True, serialize=False)),
                ('BAEM_VALOR', models.DecimalField(decimal_places=4, max_digits=5)),
                ('CLIE_CODIGO', models.ForeignKey(db_column='CLIE_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='apihc.cliente')),
                ('CUBA_CUENTA', models.ForeignKey(db_column='CUBA_CUENTA', on_delete=django.db.models.deletion.CASCADE, to='apihc.cuentabalance')),
            ],
            options={
                'db_table': 'BALANCE_CLIENTE',
                'unique_together': {('CUBA_CUENTA', 'CLIE_CODIGO', 'BAEM_FECHA')},
            },
        ),
    ]
